---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-app-deployment
  labels:
    app: employees
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
      tier: frontend
  template:
    metadata:
      labels:
        app: employees
        tier: frontend
    spec:
      containers:
        - name: employees-app
          image: miketrout/employees-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          env:
            - name: EMPLOYEES_API_URL
              value: "https://api.miketrout.dev/employees/"
          ports:
            - name: http
              containerPort: 80
