---
apiVersion: v1
kind: Service
metadata:
  name: employees-app
spec:
  type: NodePort
  selector:
    app: employees
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: http
