---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-app-deployment
  labels:
    app: employees
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      tier: frontend
  template:
    metadata:
      labels:
        app: employees
        tier: frontend
    spec:
      containers:
        - name: employees-app
          image: miketrout/employees-app
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 80
